services:
  sqlserver:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    container_name: sqlserver
    ports:
      - 1433:1433
    networks: 
      - app-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P",  "Passw0rd", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
